version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    check-flow-typings:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm run flow
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm test
                      - run: npm run build
workflows:
    build-and-test:
        jobs:
            - check-flow-typings
            - build-and-test
