version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    test:
        parameters:
            script:
                type: string
        executor: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm run << parameters.script >>
workflows:
    all-tests:
        jobs:
            - test:
                  matrix:
                      parameters:
                          os: [linux, macos]
                          script: ["build", "flow", "test"]
