version: 2.1
orbs:
    node: circleci/node@1.1.6

commands:
    install-dependencies:
        description: "Check if dependencies exist in cache and store newly installed dependencies to cache"
        steps:
            - restore_cache:
                  keys:
                      - v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - v1-npm-deps-{{ .Branch }}-
                      - v1-npm-deps-
            - run: npm install
            - save_cache:
                  key: v1-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules/
jobs:
    unit-tests:
        executor:
            name: node/default
        steps:
            - checkout
            - install-dependencies
            - run: npm test
    flow-typings:
        executor:
            name: node/default
        steps:
            - checkout
            - install-dependencies
            - run: npm run flow
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - install-dependencies
            - run: npm run build

workflows:
    build-and-test:
        jobs:
            - unit-tests
            - flow-typings
            - build
